# Generated by Django 4.1.5 on 2023-03-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_user_delete_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Eser',
        ),
    ]
