# Generated by Django 4.1.7 on 2023-03-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_superadmin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='superadmin',
            table='super_admin_auth',
        ),
    ]
