# Generated by Django 4.1.7 on 2023-03-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_superadmin_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='email',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
