# Generated by Django 4.1.7 on 2023-03-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_superadmin_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='createAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=20)),
                ('alt_mobile_no', models.CharField(max_length=20)),
                ('pan_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('accountowner', models.CharField(max_length=20)),
                ('account_no', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('_10thmark', models.FileField(upload_to='uploads/')),
                ('_12thmark', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
