# Generated by Django 4.1.7 on 2023-03-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_createadmin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='createadmin',
            table='admindata',
        ),
    ]
