# Generated by Django 4.1.7 on 2023-03-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_alter_createadmin__10thmark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createadmin',
            name='_10thmark',
        ),
        migrations.RemoveField(
            model_name='createadmin',
            name='_12thmark',
        ),
        migrations.AddField(
            model_name='createadmin',
            name='uuid',
            field=models.CharField(default=122, max_length=120),
            preserve_default=False,
        ),
    ]
