# Generated by Django 4.1.7 on 2023-03-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_remove_createadmin__10thmark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('admin_name', models.CharField(max_length=40)),
                ('administration_name', models.CharField(max_length=40)),
                ('pin_code', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'school_list',
            },
        ),
    ]
