# Generated by Django 4.1.7 on 2023-03-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_school_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_list',
            name='admin_uuid',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
