# Generated by Django 4.1.7 on 2023-03-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_school_list_school_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='check_user_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.CharField(max_length=90)),
                ('user_type', models.CharField(max_length=90)),
                ('user_permission', models.CharField(max_length=90)),
            ],
        ),
    ]
