# Generated by Django 4.1.7 on 2023-03-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_check_user_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='check_user_type',
            table='check_user_type',
        ),
    ]
