# Generated by Django 4.1.7 on 2023-05-10 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_superadmin_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='check_user_type',
        ),
        migrations.DeleteModel(
            name='createAdmin',
        ),
        migrations.DeleteModel(
            name='school_list',
        ),
        migrations.DeleteModel(
            name='SuperAdmin',
        ),
    ]
