# Generated by Django 4.1.7 on 2023-05-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_delete_check_user_type_delete_createadmin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='showPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=90)),
            ],
        ),
    ]
