# Generated by Django 4.1.7 on 2023-05-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_showplaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=90)),
                ('location', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=300)),
                ('room_area', models.CharField(max_length=200)),
                ('img1', models.BinaryField()),
                ('img2', models.BinaryField()),
                ('img3', models.BinaryField()),
                ('img4', models.BinaryField()),
                ('img5', models.BinaryField()),
                ('img6', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='show_places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=90)),
                ('name', models.CharField(max_length=90)),
                ('product_type', models.CharField(max_length=90)),
                ('products', models.TextField(max_length=900)),
            ],
        ),
        migrations.DeleteModel(
            name='showPlaces',
        ),
    ]
