# Generated by Django 4.0.6 on 2023-09-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_instadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='join_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='ssc_help_desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('number', models.CharField(max_length=90)),
                ('message', models.TextField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
    ]
