# Generated by Django 4.0.6 on 2023-09-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_join_request_ssc_help_desk'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_request',
            name='address',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='join_request',
            name='email',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='join_request',
            name='mobile_no',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='join_request',
            name='std_class',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
