# Generated by Django 4.0.6 on 2023-10-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0027_join_request_address_join_request_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=10)),
                ('program', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=10)),
                ('file', models.BinaryField()),
            ],
        ),
    ]
