# Generated by Django 4.0.6 on 2023-10-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignmentrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=20)),
                ('sem', models.CharField(max_length=20)),
            ],
        ),
    ]
